//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaneuski.Casino.WCF.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public Players()
        {
            this.RoundResults = new HashSet<RoundResults>();
            this.Players1 = new HashSet<Players>();
            this.Players2 = new HashSet<Players>();
            this.Tournaments = new HashSet<Tournaments>();
        }
    
        public int Player_ID { get; set; }
        public string PhoneNumber { get; set; }
        public double AccountBalance { get; set; }
        public bool VerifyFlag { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public bool Sex { get; set; }
        public string Email { get; set; }
        public System.DateTime Birth { get; set; }
        public int Country_Id { get; set; }
        public int Admin_Id { get; set; }
    
        public virtual Administrators Administrators { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual PassportInformations PassportInformations { get; set; }
        public virtual ICollection<RoundResults> RoundResults { get; set; }
        public virtual ICollection<Players> Players1 { get; set; }
        public virtual ICollection<Players> Players2 { get; set; }
        public virtual ICollection<Tournaments> Tournaments { get; set; }
    }
}
