//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaneuski.Casino.WpfApplication.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IGameTypeService")]
    public interface IGameTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Get", ReplyAction="http://tempuri.org/IGameTypeService/GetResponse")]
        Zaneuski.Casino.WcfServiceLibrary.GameTypesType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Get", ReplyAction="http://tempuri.org/IGameTypeService/GetResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.GameTypesType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/GetAll", ReplyAction="http://tempuri.org/IGameTypeService/GetAllResponse")]
        Zaneuski.Casino.WcfServiceLibrary.GameTypesType[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/GetAll", ReplyAction="http://tempuri.org/IGameTypeService/GetAllResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.GameTypesType[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Update", ReplyAction="http://tempuri.org/IGameTypeService/UpdateResponse")]
        void Update(Zaneuski.Casino.WcfServiceLibrary.GameTypesType gameType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Update", ReplyAction="http://tempuri.org/IGameTypeService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.GameTypesType gameType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Delete", ReplyAction="http://tempuri.org/IGameTypeService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Delete", ReplyAction="http://tempuri.org/IGameTypeService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Add", ReplyAction="http://tempuri.org/IGameTypeService/AddResponse")]
        void Add(Zaneuski.Casino.WcfServiceLibrary.GameTypesType country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTypeService/Add", ReplyAction="http://tempuri.org/IGameTypeService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.GameTypesType country);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameTypeServiceChannel : Zaneuski.Casino.WpfApplication.ServiceReference3.IGameTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameTypeServiceClient : System.ServiceModel.ClientBase<Zaneuski.Casino.WpfApplication.ServiceReference3.IGameTypeService>, Zaneuski.Casino.WpfApplication.ServiceReference3.IGameTypeService {
        
        public GameTypeServiceClient() {
        }
        
        public GameTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.GameTypesType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.GameTypesType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.GameTypesType[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.GameTypesType[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Update(Zaneuski.Casino.WcfServiceLibrary.GameTypesType gameType) {
            base.Channel.Update(gameType);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.GameTypesType gameType) {
            return base.Channel.UpdateAsync(gameType);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Add(Zaneuski.Casino.WcfServiceLibrary.GameTypesType country) {
            base.Channel.Add(country);
        }
        
        public System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.GameTypesType country) {
            return base.Channel.AddAsync(country);
        }
    }
}
