//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaneuski.Casino.WpfApplication.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IPassportInformationService")]
    public interface IPassportInformationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Get", ReplyAction="http://tempuri.org/IPassportInformationService/GetResponse")]
        Zaneuski.Casino.WcfServiceLibrary.PassportInformationType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Get", ReplyAction="http://tempuri.org/IPassportInformationService/GetResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PassportInformationType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/GetAll", ReplyAction="http://tempuri.org/IPassportInformationService/GetAllResponse")]
        Zaneuski.Casino.WcfServiceLibrary.PassportInformationType[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/GetAll", ReplyAction="http://tempuri.org/IPassportInformationService/GetAllResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PassportInformationType[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Update", ReplyAction="http://tempuri.org/IPassportInformationService/UpdateResponse")]
        void Update(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType countryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Update", ReplyAction="http://tempuri.org/IPassportInformationService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType countryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Delete", ReplyAction="http://tempuri.org/IPassportInformationService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Delete", ReplyAction="http://tempuri.org/IPassportInformationService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Add", ReplyAction="http://tempuri.org/IPassportInformationService/AddResponse")]
        void Add(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassportInformationService/Add", ReplyAction="http://tempuri.org/IPassportInformationService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType country);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPassportInformationServiceChannel : Zaneuski.Casino.WpfApplication.ServiceReference4.IPassportInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassportInformationServiceClient : System.ServiceModel.ClientBase<Zaneuski.Casino.WpfApplication.ServiceReference4.IPassportInformationService>, Zaneuski.Casino.WpfApplication.ServiceReference4.IPassportInformationService {
        
        public PassportInformationServiceClient() {
        }
        
        public PassportInformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassportInformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportInformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.PassportInformationType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PassportInformationType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.PassportInformationType[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PassportInformationType[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Update(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType countryType) {
            base.Channel.Update(countryType);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType countryType) {
            return base.Channel.UpdateAsync(countryType);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Add(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType country) {
            base.Channel.Add(country);
        }
        
        public System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.PassportInformationType country) {
            return base.Channel.AddAsync(country);
        }
    }
}
