//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaneuski.Casino.WpfApplication.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.IPlayerService")]
    public interface IPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Get", ReplyAction="http://tempuri.org/IPlayerService/GetResponse")]
        Zaneuski.Casino.WcfServiceLibrary.PlayerType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Get", ReplyAction="http://tempuri.org/IPlayerService/GetResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PlayerType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetAll", ReplyAction="http://tempuri.org/IPlayerService/GetAllResponse")]
        Zaneuski.Casino.WcfServiceLibrary.PlayerType[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetAll", ReplyAction="http://tempuri.org/IPlayerService/GetAllResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PlayerType[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Update", ReplyAction="http://tempuri.org/IPlayerService/UpdateResponse")]
        void Update(Zaneuski.Casino.WcfServiceLibrary.PlayerType countryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Update", ReplyAction="http://tempuri.org/IPlayerService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.PlayerType countryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Delete", ReplyAction="http://tempuri.org/IPlayerService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Delete", ReplyAction="http://tempuri.org/IPlayerService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Add", ReplyAction="http://tempuri.org/IPlayerService/AddResponse")]
        void Add(Zaneuski.Casino.WcfServiceLibrary.PlayerType country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Add", ReplyAction="http://tempuri.org/IPlayerService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.PlayerType country);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerServiceChannel : Zaneuski.Casino.WpfApplication.ServiceReference5.IPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerServiceClient : System.ServiceModel.ClientBase<Zaneuski.Casino.WpfApplication.ServiceReference5.IPlayerService>, Zaneuski.Casino.WpfApplication.ServiceReference5.IPlayerService {
        
        public PlayerServiceClient() {
        }
        
        public PlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.PlayerType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PlayerType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.PlayerType[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.PlayerType[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Update(Zaneuski.Casino.WcfServiceLibrary.PlayerType countryType) {
            base.Channel.Update(countryType);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.PlayerType countryType) {
            return base.Channel.UpdateAsync(countryType);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Add(Zaneuski.Casino.WcfServiceLibrary.PlayerType country) {
            base.Channel.Add(country);
        }
        
        public System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.PlayerType country) {
            return base.Channel.AddAsync(country);
        }
    }
}
