//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaneuski.ProjectTest.ServiceReference8 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference8.ITournamentRestrictionService")]
    public interface ITournamentRestrictionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Get", ReplyAction="http://tempuri.org/ITournamentRestrictionService/GetResponse")]
        Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Get", ReplyAction="http://tempuri.org/ITournamentRestrictionService/GetResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/GetAll", ReplyAction="http://tempuri.org/ITournamentRestrictionService/GetAllResponse")]
        Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/GetAll", ReplyAction="http://tempuri.org/ITournamentRestrictionService/GetAllResponse")]
        System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Update", ReplyAction="http://tempuri.org/ITournamentRestrictionService/UpdateResponse")]
        void Update(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestriction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Update", ReplyAction="http://tempuri.org/ITournamentRestrictionService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestriction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Delete", ReplyAction="http://tempuri.org/ITournamentRestrictionService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Delete", ReplyAction="http://tempuri.org/ITournamentRestrictionService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Add", ReplyAction="http://tempuri.org/ITournamentRestrictionService/AddResponse")]
        void Add(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestrictionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITournamentRestrictionService/Add", ReplyAction="http://tempuri.org/ITournamentRestrictionService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestrictionType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITournamentRestrictionServiceChannel : Zaneuski.ProjectTest.ServiceReference8.ITournamentRestrictionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TournamentRestrictionServiceClient : System.ServiceModel.ClientBase<Zaneuski.ProjectTest.ServiceReference8.ITournamentRestrictionService>, Zaneuski.ProjectTest.ServiceReference8.ITournamentRestrictionService {
        
        public TournamentRestrictionServiceClient() {
        }
        
        public TournamentRestrictionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TournamentRestrictionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TournamentRestrictionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TournamentRestrictionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Update(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestriction) {
            base.Channel.Update(tournamentRestriction);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestriction) {
            return base.Channel.UpdateAsync(tournamentRestriction);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Add(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestrictionType) {
            base.Channel.Add(tournamentRestrictionType);
        }
        
        public System.Threading.Tasks.Task AddAsync(Zaneuski.Casino.WcfServiceLibrary.TournamentRestrictionType tournamentRestrictionType) {
            return base.Channel.AddAsync(tournamentRestrictionType);
        }
    }
}
